adjust for legacy

diff --git a/src/Apps/CORE/CORE_post b/src/Apps/CORE/CORE_post
--- a/src/Apps/CORE/CORE_post
+++ b/src/Apps/CORE/CORE_post
@@ -43,6 +43,13 @@ if [ "$1" = "U" ] ; then
     fi
 
 
+    PGSERVICE="$pgservice_freedom" pgExecuteSqlFile "$wpub/vendor/Anakeen/FDL/fdl.sql"
+    RET=$?
+    if [ $RET -ne 0 ]; then
+	echo "Error executing sql file \"$wpub/FDL/fdl.sql\""
+	exit $RET
+    fi
+
     echo 'delete from permission where abs(id_acl) not in (select id from acl where acl.id_application=permission.id_application)' | PGSERVICE=$pgservice_core psql
 fi
 
