feat(ui): ank tree widget (refs #1156)
Widget d'arbre pour afficher l'arborescence de groupes dans le centre
d'administration.

Ce widget permet d'afficher des arbres avec de nombreuses branches (> 15 000)
Il n'affiche dans la page que la partie visible.

Des options permettent d'afficher le nombre de groupe ou d'utilisateurs.
La sélection peut être multiple ou simple.
Un système de filtre simple permet de n'afficher qu'une partie de l'arbre

diff --git a/smart-data-engine/src/vendor/Anakeen/CORE_init b/smart-data-engine/src/vendor/Anakeen/CORE_init
--- a/smart-data-engine/src/vendor/Anakeen/CORE_init
+++ b/smart-data-engine/src/vendor/Anakeen/CORE_init
@@ -62,6 +62,14 @@ if [ "$1" = "I" ] ; then
 	    exit $RET
     fi
 
+	log "Trying to active intarray extension on database service $pgservice_core..."
+	OUT=`PGSERVICE="$pgservice_core" psql -c 'CREATE EXTENSION IF NOT EXISTS intarray;' 2> /dev/null`
+	RET=$?
+	if [ $RET -ne 0 ]; then
+	    echo "An error occured while creating extension intarray : $RET"
+	    exit $RET
+    fi
+
     log "Executing '$wpub/vendor/Anakeen/WHAT/getprivilege.sql' in database service $pgservice_core..."
     PGSERVICE=$pgservice_core pgExecuteSqlFile "$wpub"/vendor/Anakeen/WHAT/getprivilege.sql
     RET=$?
